version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
    container_name: onproc-frontend
    networks:
      gisnet:
        aliases:
          - frontend.gisnet

networks:
  gisnet:
    external: true
